version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
