name: Build-Release Ubuntu APT

on:
  workflow_dispatch:

env:
    container_name: smarter-cli
    account: mcdaniel0073

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install packaging tools
      run: sudo apt-get install -y devscripts dput

    - name: Build source package
      run: |
        debuild -S -sa

    - name: Install Launchpad CLI client
      run: |
        sudo snap install launchpad

    - name: Get version
      id: vars
      shell: pwsh
      run: echo "::set-output name=version::$(Get-Content -Path VERSION)"

    - name: Publish to PPA
      env:
        LAUNCHPAD_TOKEN: ${{ secrets.LAUNCHPAD_TOKEN }}
      run: |
        echo $LAUNCHPAD_TOKEN | launchpad login :robot:
            dput ppa:${{ env.account }}/smarter smarter_${{ env.steps.vars.outputs.version }}_source.changes
