name: Build-Release

on:
  workflow_dispatch:

env:
    app_name: smarter

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        go: ['1.22']

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get version
      id: vars
      run: echo ::set-output name=version::$(cat VERSION)

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      id: build
      run: |
        go build -v \
        -ldflags "-X main.version=${{ steps.vars.outputs.version }}" \
        -o ./${{ env.app_name }}-${{ matrix.os }}-${{ steps.vars.outputs.version }}

    - name: Check if release exists
      id: check_release
      run: |
        RELEASE_ID=$(curl --silent \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.vars.outputs.version }}" \
          | jq '.id')
        if [ "$RELEASE_ID" != "null" ]; then
          echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: env.RELEASE_EXISTS == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.version }}
        release_name: Release ${{ steps.vars.outputs.version }}
        draft: false
        prerelease: false

    - name: Get upload URL of existing release
      if: env.RELEASE_EXISTS == 'true'
      id: get_upload_url
      run: |
        UPLOAD_URL=$(curl --silent \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.vars.outputs.version }}" \
          | jq -r '.upload_url')
        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ env.UPLOAD_URL }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./${{ env.app_name }}-${{ matrix.os }}-${{ steps.vars.outputs.version }}
        asset_name: ${{ env.app_name }}-${{ matrix.os }}-${{ steps.vars.outputs.version }}
        asset_content_type: application/octet-stream
